### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by TheManoel** [Arquisoft/InciDashboard_i1a#2]
We will start implementing the dashboard view in which the incidents can be visualized by the incident management staff. Any suggestion to improve the design of the view is welcome.

**Comment by robertops18** [comment]
At this moment, a list of the incidents and a bar chart grouping them by topic are shown in the dashboard.
We are now implementing:
- Doughnut chart ordering the incidents by status
- Map placing the incidents

**Comment by robertops18** [comment]
Currently, the dashboard is completely working. The only thing that does not work is that the other team have to assigned the agent to the incident in order to send it to kafka, because we need the agent information in order to show it in the dashboard.
When this is done, the dashboard will be finished.
